<!DOCTYPE html>
<html lang="en">
<head>
        <?php  echo $this->headTitle('Quiz Online')->setSeparator('-')->setAutoEscape(false);?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <?php echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
        
        <?php echo $this->headlink()
            ->prependStylesheet('/css/stylesheet.css')
            ->prependStylesheet('/css/bootstrap-theme.css')
            ->prependStylesheet('/css/bootstrap.css') ?>
        
        <?php echo $this->headscript()
                        ->prependFile('/js/bootstrap.js')
                        ->prependFile('/js/jquery-2.0.2.js');?>
    </head>
<body>
</body>
</html>
